spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:9998
          predicates:
            - Path=/hello/pay,/post,/get
          filters:
            - ReadRequestBody
            - SignRespBody
  http:
    encoding:
      charset: utf-8
management:
  endpoints:
    web:
      exposure:
        include: gateway

